set (KMC_EXTERNAL_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/external)

if (WIN32 OR APPLE)
	set (ASM_LIBRARY ${KMC_EXTERNAL_LOCATION}/asm/libamac64.a)
	set (BZIP_LIBRARY ${KMC_EXTERNAL_LOCATION}/bzip/libbz2.1.0.5.dylib)
	set (ZLIB_LIBRARY ${KMC_EXTERNAL_LOCATION}/zlib/libz.1.2.5.dylib)
else (WIN32 OR APPLE)
	set (ASM_LIBRARY ${KMC_EXTERNAL_LOCATION}/asm/alibelf64.a)
	set (BZIP_LIBRARY ${KMC_EXTERNAL_LOCATION}/bzip/libbz2.a)
	set (ZLIB_LIBRARY ${KMC_EXTERNAL_LOCATION}/zlib/libz.a)
endif (WIN32 OR APPLE)

add_library (asm STATIC IMPORTED)
set_target_properties (asm PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${KMC_EXTERNAL_LOCATION}/asm)
set_target_properties (asm PROPERTIES IMPORTED_LOCATION ${ASM_LIBRARY})

add_library (bzip STATIC IMPORTED)
set_target_properties (bzip PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${KMC_EXTERNAL_LOCATION}/bzip)
set_target_properties (bzip PROPERTIES IMPORTED_LOCATION ${BZIP_LIBRARY})

add_library (zlib STATIC IMPORTED)
set_target_properties (zlib PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${KMC_EXTERNAL_LOCATION}/zlib)
set_target_properties (zlib PROPERTIES IMPORTED_LOCATION ${ZLIB_LIBRARY})
