set (CPACK_PACKAGE_NAME ${PROJECT_NAME})
set (CPACK_PACKAGE_VERSION_MAJOR ${KMC_VERSION_MAJOR})
set (CPACK_PACKAGE_VERSION_MINOR ${KMC_VERSION_MINOR})
set (CPACK_PACKAGE_VERSION_PATCH ${KMC_VERSION_PATCH})
set (CPACK_PACKAGE_VENDOR ${KMC_VENDOR})
set (CPACK_PACKAGE_CONTACT ${KMC_AUTHOR_EMAIL})
set (CPACK_PACKAGE_DESCRIPTION_SUMMARY ${KMC_DESCRIPTION})
set (CPACK_PACKAGE_DESCRIPTION_FILE ${KMC_SOURCE_DIR}/README.md)

set (CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set (CPACK_DEBIAN_PACKAGE_DEPENDS "cmake (>=2.8), gcc (>=4:4.8), g++ (>=4:4.8)")

include (CPack)
